[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aa-timerpaste"
version = "0.1.1"
description = "Standalone Alliance Auth bulk timer paste plugin"
requires-python = ">=3.10"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["aa_timerpaste*"]
